### ISSUE TITLE
App crashes on startup

### ISSUE THREAD

**Issue by eaigner** [luosheng/OpenSim#11]
Console output

`29/06/16 08:48:20,539 OpenSim[74905]: fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=256 "The file “FIREBASE_LAST_TIMESTAMP” couldn’t be opened." UserInfo={NSURL=file:///Users/eaigner/Library/Developer/CoreSimulator/Devices/40420B2D-FF16-4BE0-8024-F7DF2963A47E/data/Containers/Bundle/Application/FIREBASE_LAST_TIMESTAMP, NSFilePath=/Users/eaigner/Library/Developer/CoreSimulator/Devices/40420B2D-FF16-4BE0-8024-F7DF2963A47E/data/Containers/Bundle/Application/FIREBASE_LAST_TIMESTAMP, NSUnderlyingError=0x7fe883433ab0 {Error Domain=NSPOSIXErrorDomain Code=20 "Not a directory"}}: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-800.0.30/src/swift/stdlib/public/core/ErrorType.swift, line 149`

**Comment by luosheng** [comment]
Thanks for the feedback. I'll fix this soon.

**Comment by eaigner** [comment]
Already fixed it, PR soon
