### ISSUE TITLE
High CPU and Memory usage

### ISSUE THREAD

**Issue by iMobCoding** [luosheng/OpenSim#16]
Did anyone try OpenSim with Xcode v8.1 
It works ok until I start Xcode. Then it suddenly starts eating memory and cpu until everything crashes. Anybody else?

**Comment by luosheng** [comment]
Could you post the crash log here?

**Comment by iMobCoding** [comment]
I'll try, because it takes a lot of time for crash to happen. I have 16GB of memory and it starts eating it with CPU usage jumping to 300%. Then whole system becomes unresponsive and takes some time to crash

Btw, using 0.0.6 version from releases
