### ISSUE TITLE
You cant't install OpenSim

### ISSUE THREAD

**Issue by jianghaoyuan2007** [luosheng/OpenSim#17]
Install OpenSim: `brew cask install OpenSim` 

You may modify command to `brew cask install opensim` 

➜  brew cask install OpenSim
Error: Cask 'OpenSim' definition is invalid: Bad header line: 'opensim' does not match file name

➜  brew cask search opensim
==> Exact match
opensim

**Comment by luosheng** [comment]
Closed by #18
