### ISSUE TITLE
Missing menu background when "Reduce transparency" is ON

### ISSUE THREAD

**Issue by ghost** [luosheng/OpenSim#20]
I can see that in the "draw" method of AppMenuView you're setting the background color to clear, which seems to be the problem. When I replace "clear" with a different color, it works, but I'm struggling to find a NSColor constant for the exact shade of white.

![screen shot 2016-12-15 at 19 52 45](https://cloud.githubusercontent.com/assets/1115711/21237704/5fd356de-c300-11e6-901c-c12202d55455.png)

![screen shot 2016-12-15 at 19 54 24](https://cloud.githubusercontent.com/assets/1115711/21237710/630706a2-c300-11e6-8256-2d2a165fd163.png)

**Comment by luosheng** [comment]
Nice catch! I'll see what I can do with it. Thanks!

**Comment by philosopherdog** [comment]
I'm having the same issue. I think many devs turn reduced transparency off.
