### ISSUE TITLE
make simulator not responding when using Xcode 9 beta 2

### ISSUE THREAD

**Issue by yam-liu** [luosheng/OpenSim#29]
simulator not responding when open opensim, and the latter dont have a list of simulators

**Comment by luosheng** [comment]
Do you happen to have both Xcode 8 and Xcode 9 beta installed?

**Comment by yam-liu** [comment]
yes，but not run both at the same time
Sheng Luo <notifications@github.com>于2017年7月4日 周二09:51写道：

**Comment by yam-liu** [comment]
Could you please release a new version with #30 ?
