### ISSUE TITLE
10.13 Beta Xcode8/9不工作

### ISSUE THREAD

**Issue by mqiezi** [luosheng/OpenSim#31]
10.13 Beta Xcode8/9不工作 ，是不是还没有适配？

**Comment by luosheng** [comment]
是不是同时装了两个 Xcode？

**Comment by mqiezi** [comment]
是的？要修改什么吗？

**Comment by luosheng** [comment]
直接试下最新的 0.3.0 版本吧，之前有试过修复

**Comment by mqiezi** [comment]
依然存在这个问题

**Comment by luosheng** [comment]
有具体一点的现象描述吗？

**Comment by mqiezi** [comment]
下图这样，看不到任何关于模拟器的
![如图](http://image-1254284839.cossh.myqcloud.com/QQ20170905-165528.png)

**Comment by luosheng** [comment]
能不能贴一下命令行里 `xcrun simctl list -j devices` 的结果？

**Comment by mqiezi** [comment]
{
  "devices" : {
    "iOS 11.0" : [
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "iPhone 5s",
        "udid" : "EBAD7FEA-9BA4-4711-8091-EBC2FB5FA828"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "iPhone 6",
        "udid" : "E3336A15-C8B6-44EE-ACC8-B3FEE7326EA7"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "iPhone 6 Plus",
        "udid" : "F714B57D-B15C-40D3-9EC7-3168EEB9D525"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "iPhone 6s",
        "udid" : "B6CADBCF-A322-4E79-8E18-CDD21A791CE5"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "iPhone 6s Plus",
        "udid" : "206A7EA1-23AA-4044-9B68-3FF1BAD0D6D9"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "iPhone 7",
        "udid" : "0DB79CB9-04AE-4B7B-A314-9C4F5D1DDD39"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "iPhone 7 Plus",
        "udid" : "B70D2D9D-40FA-49E9-A0FB-452E6C329913"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "iPhone SE",
        "udid" : "DB556548-C470-4A6C-B88E-9E9DB925900A"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "iPad Air",
        "udid" : "40B7E9C7-8FDE-4CB6-A2E5-39652E0B74E3"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "iPad Air 2",
        "udid" : "7F9BD62D-5E84-48A1-9B5E-5E7A6AA1F5EA"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "iPad (5th generation)",
        "udid" : "DEABC82D-52D4-450A-B203-0878A522E6B6"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "iPad Pro (9.7 inch)",
        "udid" : "45945029-2DB7-4B7C-AC67-235A45D76661"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "iPad Pro (12.9 inch)",
        "udid" : "5CFE8A2B-258A-4132-B66A-D054FE2A3767"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "iPad Pro (12.9-inch) (2nd generation)",
        "udid" : "CEE65ABD-5CA3-450D-9991-9572CCD3E06B"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "iPad Pro (10.5-inch)",
        "udid" : "39AEFC80-49BA-4423-8A44-17A0F61B3F6A"
      }
    ],
    "iOS 9.1" : [

    ],
    "com.apple.CoreSimulator.SimRuntime.iOS-10-2" : [
      {
        "state" : "Shutdown",
        "availability" : " (unavailable, runtime profile not found)",
        "name" : "iPhone SE",
        "udid" : "4C02EE1B-4BF3-42CC-A616-5694826127DC"
      }
    ],
    "tvOS 11.0" : [
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "Apple TV 1080p",
        "udid" : "E727EF9C-572D-4BBE-918E-131C6CC32884"
      }
    ],
    "com.apple.CoreSimulator.SimRuntime.tvOS-10-2" : [
      {
        "state" : "Shutdown",
        "availability" : " (unavailable, runtime profile not found)",
        "name" : "Apple TV 1080p",
        "udid" : "CF299A58-0FEF-4011-90A5-FEC8083A216F"
      }
    ],
    "com.apple.CoreSimulator.SimRuntime.watchOS-3-2" : [
      {
        "state" : "Shutdown",
        "availability" : " (unavailable, runtime profile not found)",
        "name" : "Apple Watch - 38mm",
        "udid" : "FAB23106-7756-4A09-B707-B986823D2F9D"
      },
      {
        "state" : "Shutdown",
        "availability" : " (unavailable, runtime profile not found)",
        "name" : "Apple Watch - 42mm",
        "udid" : "422FA902-2146-42A9-A477-A617D6B3DDA5"
      },
      {
        "state" : "Shutdown",
        "availability" : " (unavailable, runtime profile not found)",
        "name" : "Apple Watch Series 2 - 38mm",
        "udid" : "4CF7F984-E7B3-4109-B1A8-C40FA37D8C14"
      },
      {
        "state" : "Shutdown",
        "availability" : " (unavailable, runtime profile not found)",
        "name" : "Apple Watch Series 2 - 42mm",
        "udid" : "BAED4C3B-8218-4CA2-A9D1-667AA4FECFBF"
      }
    ],
    "iOS 8.1" : [

    ],
    "com.apple.CoreSimulator.SimRuntime.iOS-10-3" : [
      {
        "state" : "Shutdown",
        "availability" : " (unavailable, runtime profile not found)",
        "name" : "iPhone 5",
        "udid" : "03EF19DD-DD27-41BD-AFBA-4D5BD5DAD085"
      },
      {
        "state" : "Shutdown",
        "availability" : " (unavailable, runtime profile not found)",
        "name" : "iPhone 5s",
        "udid" : "692E2E5F-4F09-479E-8B41-5F5D3B3D46C1"
      },
      {
        "state" : "Shutdown",
        "availability" : " (unavailable, runtime profile not found)",
        "name" : "iPhone 6",
        "udid" : "E1E2078D-9F83-4291-B460-B4230CD328CD"
      },
      {
        "state" : "Shutdown",
        "availability" : " (unavailable, runtime profile not found)",
        "name" : "iPhone 6 Plus",
        "udid" : "FFE151A4-606D-4F97-84F6-37D095C3DD7D"
      },
      {
        "state" : "Shutdown",
        "availability" : " (unavailable, runtime profile not found)",
        "name" : "iPhone 6s",
        "udid" : "13E1C752-CF1B-4C65-B36E-9A92F8ADD943"
      },
      {
        "state" : "Shutdown",
        "availability" : " (unavailable, runtime profile not found)",
        "name" : "iPhone 6s Plus",
        "udid" : "94CC55F6-A9C4-47F3-B393-66306208457C"
      },
      {
        "state" : "Shutdown",
        "availability" : " (unavailable, runtime profile not found)",
        "name" : "iPhone 7",
        "udid" : "C6607990-E98D-43EC-AB1C-40736FE0ED53"
      },
      {
        "state" : "Shutdown",
        "availability" : " (unavailable, runtime profile not found)",
        "name" : "iPhone 7 Plus",
        "udid" : "4C7C463F-9993-4F5E-A436-89E2BFB58C16"
      },
      {
        "state" : "Shutdown",
        "availability" : " (unavailable, runtime profile not found)",
        "name" : "iPhone SE",
        "udid" : "790515D6-6EE6-460B-92A1-CD9C5D432D8D"
      },
      {
        "state" : "Shutdown",
        "availability" : " (unavailable, runtime profile not found)",
        "name" : "iPad Air",
        "udid" : "CB96B1A4-4874-4658-8830-92AA583041E1"
      },
      {
        "state" : "Shutdown",
        "availability" : " (unavailable, runtime profile not found)",
        "name" : "iPad Air 2",
        "udid" : "56623519-EED3-4D06-A57D-CD37DB535BE7"
      },
      {
        "state" : "Shutdown",
        "availability" : " (unavailable, runtime profile not found)",
        "name" : "iPad (5th generation)",
        "udid" : "EA5CAD98-2880-4DA6-8E20-483623C82C75"
      },
      {
        "state" : "Shutdown",
        "availability" : " (unavailable, runtime profile not found)",
        "name" : "iPad Pro (9.7 inch)",
        "udid" : "8C727D90-1D47-444F-B975-28240D9EB973"
      },
      {
        "state" : "Shutdown",
        "availability" : " (unavailable, runtime profile not found)",
        "name" : "iPad Pro (12.9 inch)",
        "udid" : "9598A7AE-5353-42E6-89AA-DB3EEB74AD69"
      },
      {
        "state" : "Shutdown",
        "availability" : " (unavailable, runtime profile not found)",
        "name" : "iPad Pro (12.9-inch) (2nd generation)",
        "udid" : "44A2C3EF-B381-4604-AA18-E74E68FA29F0"
      },
      {
        "state" : "Shutdown",
        "availability" : " (unavailable, runtime profile not found)",
        "name" : "iPad Pro (10.5-inch)",
        "udid" : "B72803FB-97B9-4D47-A5F8-7D3631930FAE"
      }
    ],
    "watchOS 4.0" : [
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "Apple Watch - 38mm",
        "udid" : "3CAB92C3-0013-4EBD-BFA5-D50E496B0B68"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "Apple Watch - 42mm",
        "udid" : "9F338205-F4B7-415C-9E97-D1E452C547E0"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "Apple Watch Series 2 - 38mm",
        "udid" : "45C193D9-F930-48A6-88AA-74D17B5AFE5A"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "Apple Watch Series 2 - 42mm",
        "udid" : "478FD55D-87F0-4D3C-8500-D1F8CE830A11"
      }
    ]
  }
}
