### ISSUE TITLE
ios11 模拟器的问题

### ISSUE THREAD

**Issue by birneysky** [luosheng/OpenSim#32]
首先十分感谢您开发出了开源好用的工具，提高了我的工作效率！
现在我升级前到了xcode9 Version 9.0 beta 6 (9M214v) 移除了之前xcode8，发现xcode9下 OpenSim 不能预览到  ios11 模拟器中的应用，希望您能抽出宝贵的时间修复一下该问题，再次感谢。

**Comment by nilsnilsnils** [comment]
OpenSim don't find my Simulator folders. 
Refresh takes no effect. Restart PC or App doesn't help.

Folder for Simulators:
/Users/nils/Library/Developer/CoreSimulator/

XCode 9, macOS High Sierra 10.13,

**Comment by luosheng** [comment]
Duplicated as #37
