### ISSUE TITLE
"Copy Sandbox Path to Pasteboard" not working

### ISSUE THREAD

**Issue by JamesKuang** [luosheng/OpenSim#34]
On Xcode 9.0 and macOS 10.12.6. Tried to use "Copy Sandbox Path to Pasteboard" but nothing is copied to pasteboard. Tried it for iPhone 8 and iPhone X iOS 11 simulators.

**Comment by apparition47** [comment]
Noticed the same issue on 10.13. Opened a PR to fix it.
