### ISSUE TITLE
Licensing terms

### ISSUE THREAD

**Issue by profburke** [luosheng/OpenSim#4]
Thanks for all your efforts for this project. It's a nice job and a great alternative to SimPholders.

I am planning on creating a similar tool that is command line based, rather than graphical and I was wondering what re-use terms you had in mind for the project. Was your intention for the code to be GPLed or available under an MIT-style license or something else entirely?

Thanks.

**Comment by luosheng** [comment]
Hi profburke, thanks for your interest in the project. It's under an MIT license and I'll add a LICENSE file to clarify that. I'd appreciate it if you can give me some credit in your project though. :-)

**Comment by profburke** [comment]
@luosheng thanks for the quick response. Having a license file will make my employer a lot happier.

I will certainly give you prominent credit in the project. I had at first thought about implementing it as an extension to your project and sending you a Pull Request. But I think it's enough different that it makes more sense to have a separate project.
