### ISSUE TITLE
XCode 10.1 not supported -> isAvailable

### ISSUE THREAD

**Issue by nilsnilsnils** [luosheng/OpenSim#43]
The key "availability" has changed to "isAvailable". 
Therefore no devices will be found. 
-> SimulatorController.swift:37

**Comment by johndpope** [comment]
https://github.com/luosheng/OpenSim/pull/44

**Comment by Mirconet** [comment]
Change SimulatorController.swift:34 -> if let deviceList = deviceList as? [[String:AnyObject]] {
The value for the key "isAvailable" is a boolean.
Then change SimulatorController.swift row 36 - 39 to:

if let state = deviceJson["state"] as? String,
   let availability = deviceJson["availability"] as? String,
   let name = deviceJson["name"] as? String,
   let udid = deviceJson["udid"] as? String {

**Comment by dungc** [comment]
Thank you @Mirconet,it's worked.

**Comment by Bunn** [comment]
I have a PR for this: 
https://github.com/luosheng/OpenSim/pull/45

**Comment by ogezue** [comment]
when is a release planned?

**Comment by RomainQuidet** [comment]
+1 need an update :) thanks !

**Comment by RomainQuidet** [comment]
The pull request #44 does not correct the issue.

the json parsed is structure as this for available devices:
`{
        "availability" : "(available)",
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 5s",
        "udid" : "769F8F0A-66FA-41F5-8FAA-17E803044DB8",
        "availabilityError" : ""
      }`

and for not available device:
`{
        "availability" : "(unavailable, runtime profile not found)",
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple TV 4K (at 1080p)",
        "udid" : "352FBDD8-0776-45CB-8CEE-97625CB8F9F0",
        "availabilityError" : "runtime profile not found"
      }`

**Comment by RomainQuidet** [comment]
So isAvailable json key is used now, but availability is still (available) or (unavailable etc...)

**Comment by RomainQuidet** [comment]
anyway, the command line used `xcrun simctl list -j devices` does not list my ios 12 simulator devices ....

**Comment by RomainQuidet** [comment]
it does list it but the json parser fails now as availability is not anymore a string but a boolean. Swift dictionary must be homogeneous... as? [[String: String]] fails

**Comment by Bunn** [comment]
Fixed on the latest release: https://github.com/luosheng/OpenSim/releases/tag/0.4.1
