### ISSUE TITLE
OpenSim don't show anything

### ISSUE THREAD

**Issue by CoderMaurice** [luosheng/OpenSim#48]
I used Xcode to run the source code and it is correct.
Then I open the app but still nothing.
![image](https://user-images.githubusercontent.com/22311615/48877139-d42d7f00-ee3c-11e8-86dc-d02959706e25.png)

**Comment by qq912276337** [comment]
the same! how to solve it ?

**Comment by Bunn** [comment]
Can you verify that you are using the latest version `0.4.1`? There was an issue on Xcode 10.1 that was fixed on the newest release. https://github.com/luosheng/OpenSim/releases/tag/0.4.1

**Comment by CoderMaurice** [comment]
Yes, after this problem, I realized that the version needs to be updated, but it has not changed since the update.

**Comment by Bunn** [comment]
Can you give a try running it from the `develop` branch and see if it works? If it doesn't check that your simulators have at least one app installed since it doesn't list simulators without apps, and post the result of this command on your terminal here `xcrun simctl list -j`

thanks.

**Comment by CoderMaurice** [comment]
I found the value in Xcode-Preferences-Locations-Command Line Tools is empty, i rest it and everything is fine.
thanks @Bunn 

and @qq912276337, check it.

<img width="802" alt="wx20181127-141309 2x" src="https://user-images.githubusercontent.com/22311615/49062470-3c220200-f24f-11e8-9f86-5fc7bd16ae7d.png">
