### ISSUE TITLE
No simulators found on macOS Catalina beta (Xcode10/11)

### ISSUE THREAD

**Issue by rmvz3** [luosheng/OpenSim#53]
It seems it doesn't see any simulator running macOS Catalina Beta 1. Both, Xcode10 and Xcode11 beta.

**Comment by moheny** [comment]
Same here. I think what mess it up is not the OS, is having both xcode10 and Xcode 11 beta on the same OS, this is only my guess since it's not working on Mojave as well.

**Comment by Bunn** [comment]
Please give it a try on the newest version (0.4.3).
I'll leave this ticket open since I don't have Catalina to test, but let me know if it works :)

Thanks

**Comment by rmvz3** [comment]
Yes! It works like a charm! Thank you very much. I NEED this app :D
